# Programación y NumPy

En la primera parte de este notebook seguiremos explorando algunas cuestiones de programación. En la segunda parte, empezaremos a trabajar con NumPy, nuestra primera librería.

## 1. Programación

### 1.1 Operaciones Lógicas

Comencemos viendo cómo implementar lo que vimos en la bitácora de operaciones lógicas. Te recomendamos tener la bitácora cerca así puedes consultarla.

En primer lugar, la operación `not` es simplemente la negación del booleano.

In [1]:
variable_1 = True
print(not(variable_1))

variable_2 = False
print(not(variable_2))

False
True


La operación `and` nos devuelve `True` unicamente cuando ambas variables son verdaderas. Experimentar con la celda inferior y comprobar su tabla de verdad.

In [6]:
variable_1 = True
variable_2 = False
print(variable_2 and variable_2)
print(variable_1 and variable_2)
print(variable_2 and variable_1)
print(variable_1 and variable_1)

False
False
False
True


**Ejercicio:** comprobar la tabla de verdad de la operación `or` jugando con la celda siguiente. Viene con trampa(s).

In [7]:
variable_1 = True
variable_2 = False

print(variable_1 or variable_2)
print(variable_2 or variable_1)
print(variable_1 or variable_1)
print(variable_2 or variable_2)


True
True
True
False


### 1.2 Estructuras de control - Condicionales

Los condicionales nos permiten ejecutar o no un bloque de codigo dependiendo de ciertas condiciones. En lenguaje coloquial, vendrían a ser del estilo de "Si se cumple esta condición, hace A. Si no se cumple, hace B", donde B puede ser, simplemente, no hacer nada. Veamos qué formas toman.

### 1.2.1 If

El condicional más simple es el `if`. Para mayor claridad escribiremos la condicion entre parentesis (), aunque esto no es necesario. Su estructura es 

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
```

Veamos algunos ejemplos:

In [8]:
valor = 15
if (valor > 10):
    print('El valor es mayor que 10')

El valor es mayor que 10


Prestar atención a que la condición debe ser un booleano

In [9]:
print(valor > 10)
print(type(valor > 10))

True
<class 'bool'>


**Nota:** para comparar variables, tenemos las operaciones menor `<`, mayor `>`, igualdad `==`, menor o igual  `<=`, y mayor o igual `>=`.

In [11]:
#https://www.w3schools.com/python/python_operators.asp
print(3 == 3)
print(3!=3)
print(3 <= 3)
print(3 >= 3)
print(3 > 3)


True
False
True
True
False


### 1.2.2 If, Else

A la estrucutra con `if` se le puede agregar otro bloque de codigo que se ejecute si la condición exigida NO se cumple. Esto se logra mediante la expresión `else`.

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
else:
    Si NO se cumple la condición, se ejecutan estas líneas de código
```

In [12]:
nombre = 'Pedro'

if (nombre == 'Juan'):
    print('Esta persona se llama Juan')
else:
    print('Esta persona NO se llama Juan')

Esta persona NO se llama Juan


Prestar atención, nuevamente, a que la condición - lo que está entre paréntesis - es un booleano.

In [13]:
'Juan'=='Pedro'

False

### 1.2.3 If, Elif, Else
A esta estructura se le pueden sumar tantas condiciones encadenadas como uno desee, mediante la expresión `elif`. El orden en que se van chequeando las condiciones depende de su posición, priemero se chequea el `if`, luego el primer `elif`, luego el segundo, y así sucesivamente.

``` python
if condicion_1:
    Si se cumple la condicion_1 , se ejecutan estas líneas de código
elif condicion_2:
    Si se cumple la condicion_2 , se ejecutan estas líneas de código
elif condicion_3:
    Si se cumple la condicion_3 , se ejecutan estas líneas de código
else:
    Si NO se cumple ninguna de las condiciones anteriores, se ejecutan líneas celdas de código
```


In [14]:
edad = 20

if (edad < 18):
    print('Esta persona tiene menos de 18 años')
elif (edad > 18):
    print('Esta persona tiene mas de 18 años')
else:
    print('Esta persona tiene justo 18 años')

Esta persona tiene mas de 18 años


**Ejercicio**: Escriba un bloque de código que, dado un número, imprima la frase "El numero es par" si el número es par o la frase "El numero es impar" si no lo es.

In [45]:
numero = 17

#si es divisible por 2 es par 
if ((numero%2) == 0):
    print('El numero es par')
else: #caso contrario es impar
    print('el numero es impar')


el numero es impar


### 1.3 Combinando estructuras de código

Las estructuras de loops que vimos en la bitácora anterior y condicionales que aprendimos se pueden combinar para generar comportamientos más complejos. Supongamos que tenemos una lista de edades y nos queremos quedar con aquellas que sean mayores que 18 años. Podemos hacer lo siguiente:

In [46]:
lista_de_edades = [4,20,15,29,11,42,10,18]
lista_mayores = []

for edad in lista_de_edades:
    if (edad >= 18):
        # Agremos a la lista de mayores
        lista_mayores.append(edad)

print(lista_mayores)

[20, 29, 42, 18]


### 1.4 Operaciones lógicas y estructuras de control

A veces, queremos ejecutar una línea de código si se cumple más de una condición. Esto se puede lograr fácilmente usando las operaciones lógicas que vimos. Supongamos que tenemos una lista de números, y queremos seleccionar aquellos que cumplan ciertas propiedades. Por ejemplo, que son mayores o iguales que 5 y menores que 20. Podríamos hacer lo siguiente:

In [49]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5:
        if numero < 20:
            seleccionados.append(numero)
print(seleccionados) #condiciones anidadas


numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if ((numero >= 5) & (numero < 20)):
        seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]
[6, 17, 5, 6, 13, 15]


Notar que los números seleccionados cumplen los requisitos que pedimos. Pero también podríamos hacerlo así:

In [50]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5 and numero < 20: #((numero >= 5) & (numero < 20))
        seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


El resultado es el mismo. Si bien esta forma es más compacta, no necesariamente implica que sea mejor. Uno/a elije hacerlo de una u otra forma según lo que le parezca más claro; si ambas condiciones juntas son difíciles de leer, tal vez puedes usar la primera forma.

**Ejercicio**: Modifica el ejemplo anterior para que seleccione aquellos números **mayores** que 5 **o** impares.

In [53]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if (numero > 5) or ((numero%2)!=0):
        seleccionados.append(numero)
print(seleccionados)

[3, 1, 6, 17, 3, 89, 5, 6, 13, 25, 3, 23, 1, 15]


### Ejercitación

**Ejercicio 1**: ¿Qué pasa si sumás, restás, multiplicás o dividís booleanos? Pruébalo e interpreta.

In [57]:
print(True + True)
print(True + False)

print(True - True)
print(True - False)

print(True * True)
print(True * False)

print(True / True)
print(False / True)

print('Los booleanos true=1 y false=0')


2
1
0
1
1
0
1.0
0.0
Los booleanos true=1 y false=0


**Ejercicio 2**: Hacer una estructur `if/else` que compare dos variables numéricas `A` y `B` y que decida cuál es mayor e imprima en pantalla "A es mayor que B" o "B es mayor que A" . 

In [61]:
A = 5
B = 4

if (A>B):
    print('A es mayor que B')
elif (A<B):
    print('B es mayor que A')
else:
    print('A es igual a B')


A es mayor que B


**Ejercicio 3 - Challenge**: Dada la siguiente lista de numeros:

In [ ]:
numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5]

Escribir una rutina que calcule la suma de los números **pares menores que 5** en esta lista. **Pistas:** 
* Hay muchas formas de hacerlo, si piensas en más de una, mejor. Pero trata de tomar los ejemplos que vimos en este notebook.
* El resultado es 20. 
* Recuerda que puedes inicializar una variable en cero, y luego ir modificándola en un loop. Hicimos algo así en el notebook de la bitácora anterior con una variable que llamamos `i` y en el ejercicio 5 del mismo notebook.

In [3]:
numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5]

suma=0
for i in numeros:
    if ((i<5) & ((i%2)==0)):
        suma+=i
print(suma)

20


**Ejercicio 4 - Challenge Opcional**: Dada la siguiente lista de numeros:

In [ ]:
numeros_en_texto = ['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1', '3', '2', '2', '3', '3', '3', '2', '2', '1', '1']
print(numeros_en_texto)

Calcule la suma de los unos (1) y los tres (3) en esta lista. Nuevamente, hay muchas formas de hacerlo. **Pistas:** 
* El resultado es 210.
* Puede reciclar código de ejemplos anteriores y del ejercicio anterior.
* Se pueden comparar strings, ver ejemplo más arriba.
* También se pueden forzar tipos de datos. Por ejemplo, `int('4')` nos devuelve un 4, entero.
* Se puede resolver sin usar todas las pistas

In [3]:
numeros_en_texto = ['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1', '3', '2', '2', '3', '3', '3', '2', '2', '1', '1']
suma=0
for Num in numeros_en_texto:
    if ((Num == '1') or (Num == '3')):
        suma+=int(Num)
print(suma)

#print(numeros_en_texto.count('3'), numeros_en_texto.count('1')) a = 60 * 3 b = 30 c = a + b print(c) 
b = [int(x) for x in numeros_en_texto] 
c = b.count(1)*1 + b.count(3)*3 print(c) 
#https://www.w3schools.com/python/ref_func_map.asp 
# COMPLETAR numeros_int = list(map(int, numeros_en_texto)) suma = 0 # usamos la función map, para aplicar la fx int a cada elemento de la lista numeros_en_texto # se propdría sobrescribir la misma lista, en vez de crear una nueva, pero, a efectos de este ejercicio # no habrá problemas de memoria/performance. for numero in numeros_int: if(numero in (3,1)): suma += numero print('La suma es', suma)

210


## 2. Numpy
https://aprendeconalf.es/python/manual/numpy.html

Empezaremos a dar nuestros primeros pasos con NumPy. Es muy importante que googlees y consultes la documentación. Si no la instalaste, ahora es un buen momento.

Cuando queremos usar una librería, primero debemos importarla. Más adelante veremos qué significa importar una librería, pero podemos entenderlo como que es un aviso a Python de que vamos a incorporar nuevas funcionalidades; en este caso, desde NumPy.

In [4]:
import numpy as np

Ahora nuestro ambiente de trabajo sabe que si ponemos algo del estilo `np.` significa que esa funcionalidad la debe buscar en NumPy. **Importante:** Si la librería NO se instaló correctamente, te saltará un mensaje de error.

El principal tipo de dato sobre el que trabaja NumPy son los arreglos o arrays. Los arreglos son parecidos a listas y, de hecho, se pueden crear a partir de ellas.

In [65]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero son más que una lista. Algunas cosas que no se podían hacer con las listas ahora sí se pueden con arreglos. Recordemos que sumarle un número a toda la lista no estaba permitido

In [71]:
#lista + 1
lista * 3

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

¡Pero ahora con los arreglos sí!

In [70]:
arreglo + 1

array([ 0,  3,  6,  9, 12, 15])

Esto simplifica mucho hacer cuéntas. Pero no es sólo sumar, también muchas otras operaciones:

In [69]:
print(arreglo - 5)
print(arreglo / 2)
print(arreglo*4)
print(arreglo**2)

[-5 -4 -3 -2 -1  0]
[0.  0.5 1.  1.5 2.  2.5]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


Comprobar que, salvo la multiplicación, ninguno estaba permitido en listas. ¿Qué hace la multiplicación en el caso de una lista? ==> concatena la misma lista n veces

### 2.1 Creación de arreglos

Si bien podemos crear arreglos a partir de listas, NumPy viene con muchas funciones para hacerlo. Veamos algunas.

Una muy utilizada es `np.arange([start,] stop[, step,], dtype=None)`
Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.




Consulta su documentación. Otra opción es que, en una celda de código, escribas `np.arange` y aprietes `shift` + `tab`. De esa forma, te aparecerá la ayuda.

Juega un poco con el ejemplo a continuación.

In [92]:
arreglo = np.arange(0,10)
arreglo = np.arange(0,10,1)
arreglo = np.arange(0,10,2)
arreglo =np.linspace(0,10,num=5)
print(arreglo)
#genera un arreglo numerico desde start, hasta end, salteando step. 
#Esta equiespaciado entre los enteros. en ese caso usar linspace.


[ 0.   2.5  5.   7.5 10. ]


**Ejercicio:** investiga y crea ejemplos con las siguientes funciones

[np.arrays](https://aprendeconalf.es/python/manual/numpy.html#Creaci%C3%B3ndearrays)

* `np.linspace`. Presta particular atención a cómo se diferencia de `np.arange`.

Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia de n valores equidistantes desde inicio hasta fin

**np.linspace(start,  stop,
                  num=50, #indica en cuantas veces particiono el vector en espacios iguales
                endpoint=True, #incluye el valor stop
                retstep=False, dtype=None,  axis=0)**

La diferencia con np.arrange es que este ultimo crea un array de una dimensión cuyos elementos son la secuencia desde inicio hasta fin tomando valores cada salto. 
         
        arreglo = np.arange(0,10,2)
        arreglo =np.linspace(0,10,num=5)
Ambos estan particionados en 5 espacios pero el resultado es distinto



* `np.zeros` y `np.ones`
Crea arrays de ceros y unos, con dimension x,y,z,k,n...


In [115]:
arreglo = np.arange(0,10,2)
print(arreglo)
arreglo2 =np.linspace(0,10,num=5)
print(arreglo2)
print(np.zeros((3,4)))

print()
print(np.ones((3,3)))

print()
print(np.identity(3))

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [119]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arreglo_2d)


[[1 2 3 4]
 [5 6 7 8]]


Notar que tiene dos filas y cuatro columnas. Podemos descubrir esto sin imprimirlo en pantalla, sino usando la propiedad `.shape` del arreglo.

In [118]:
print(arreglo_2d.shape)

(2, 4)


Primero aparece el número de filas y luego el de columnas. ¿Qué estructura de dato es `(2, 4)`?
*Matriz*

Otro ejemplo:

In [120]:
arreglo_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arreglo_2d)
print(arreglo_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Si queremos saber cuántos elementos tiene, podemos usar `.size`

In [121]:
print(arreglo_2d.size) 

8


### 2.3 Funciones que operan sobre arreglos

Los arreglos de NumPy incorporan un montón de funciones que operan sobre los arreglos. Veamos algunos ejemplos.

In [122]:
un_arreglo = np.array([-100,2,3,17,25,1,95])
print(un_arreglo.min())
print(un_arreglo.max())

-100
95


En el caso 2D, podemos pedir que estas funciones operen sobre todo el arreglo, o por ejes.



In [123]:
# No te preocupes si no entiendes lo que hace esta celda
arreglo_2d = np.arange(9)
np.random.shuffle(arreglo_2d) #desordena de manera aleatoria los valores del arreglo
arreglo_2d = arreglo_2d.reshape((3,3)) #modifico el vector 1x9 por matriz 3x3
print(arreglo_2d)

[[0 2 3]
 [6 5 1]
 [8 7 4]]


Trata de entender la diferencia entre las siguientes instrucciones:

In [124]:
print(arreglo_2d.max())  #calcula el maximo de todo el arreglo
print(arreglo_2d.max(axis = 0)) #calcula el maximo por columna
print(arreglo_2d.max(axis = 1)) #calcula el maximo por fila

8
[8 7 4]
[3 6 8]


### Últimos comentarios

* No dijimos nada sobre indexado ni slicing. Esto se debe a que, para arreglos 1D, es similar que para la listas. Para arreglos 2D, es apenas más complicado. Para estudiarlo, jugar con la siguiente celda:

In [125]:
arreglo_2d = np.arange(9).reshape(3,3) #genera un vector del 0 a 9 y lo transforma en matrix 3x3
print(arreglo_2d)
print(arreglo_2d[1,:]) #tomo la segunda fila y todas las columnas

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


* Podemos usar `arreglo.max()` o `np.max(arreglo)`. Esto no es válido solamente para la función `max()`, sino también para casi todas las funciones que operen sobre arreglos. 

In [126]:
print(np.min(un_arreglo), un_arreglo.min())

-100 -100


Existe mucho más - realmente mucho más - para decir sobre NumPy. Pero mucho irá apareciendo a medida que lo vayamos necesitando. Y, además, ¡este notebook ya es muy largo!

### Ejercitación

**Ejercicio 1**: Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: `linspace`

In [1]:
import numpy as np
Arreglo=np.linspace(0,9,100,endpoint=True)
print(Arreglo)
print(Arreglo.size)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
10


**Ejercicio 2:** crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [6]:
import numpy as np
Arreglo=np.zeros(20)
Arreglo[0:15]=1 #[:15]
print(Arreglo)
print(Arreglo.size)


20
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


**Ejercicio 3:** crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [4]:
import numpy as np
Arreglo=np.zeros(50)
Arreglo[:25]=np.arange(0,25)#[0:25], el cero esta de mas porque es por default
print(Arreglo)
print(Arreglo.size)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
50


**Ejercicio 4:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0 
0 2 0
0 3 0
```

In [2]:
import numpy as np
Arreglo=np.zeros((3,3))
Arreglo[:,1]=[1,2,3]
print(Arreglo.shape)
print(Arreglo)


(3, 3)
[[0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]]


**Ejercicio 5:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 
0 1 0
0 0 1
```

In [11]:
import numpy as np
##forma 1
Arreglo=np.zeros((3,3))
for i in np.arange(0,3):
    for j in np.arange(0,3):
            if (i==j):
                Arreglo[i,j]=1
            else:
                Arreglo[i,j]=0             
print(Arreglo.shape)
print(Arreglo)
print()

##forma 2

identidad=np.identity(3)
print(identidad)
print()
identidad2=np.eye(3) #en este caso es igual a identidad pero identidad funcioa con matrices cuadradas NxN y eye con matrices rectangulares NxM
print(identidad2)
print()
##forma 3
Arreglo=np.zeros((3,3))
np.fill_diagonal(Arreglo,Arreglo.diagonal()+1)
print(Arreglo)
print()
##forma 4
n=3
Arreglo=np.zeros((3,3))
Arreglo.flat[::n+1]=1 #sustituye la diagonal con un array de 1 directamente
print(Arreglo)
#A flatiter iterator is returned by x.flat for any array x. It allows iterating over the array as if it were a 1-D array, either in a for-loop or by calling its next method.



(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:

np.fill_diagonal() funciona sin que sea matriz cuadrada
Signature: np.fill_diagonal(a, val, wrap=False)
Docstring:
Fill the main diagonal of the given array of any dimensionality.

For an array `a` with ``a.ndim >= 2``, the diagonal is the list of
locations with indices ``a[i, ..., i]`` all identical. This function
modifies the input array in-place, it does not return a value.

Parameters
----------
a : array, at least 2-D.
  Array whose diagonal is to be filled, it gets modified in-place.

val : scalar
  Value to be written on the diagonal, its type must be compatible with
  that of the array a.

wrap : bool
  For tall matrices in NumPy version up to 1.6.2, the
  diagonal "wrapped" after N columns. You can have this behavior
  with this option. This affects only tall matrices.

See also
--------
diag_indices, diag_indices_from

Notes
-----
.. versionadded:: 1.4.0

This functionality can be obtained via `diag_indices`, but internally
this version uses a much faster implementation that never constructs the
indices and uses simple slicing.

Examples
--------
>>> a = np.zeros((3, 3), int)
>>> np.fill_diagonal(a, 5)
>>> a
array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

AttributeError: module 'numpy' has no attribute 'flat'

TypeError: identity() missing 1 required positional argument: 'n'

**Ejercicio 6:** crear un arreglo 2D de 100 filas y 100 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 ... 0 0 0 
0 1 0 ... 0 0 0
0 0 1 ... 0 0 0
...  
0 0 0 ... 1 0 0
0 0 0 ... 0 1 0
0 0 0 ... 0 0 1
```

In [160]:
import numpy as np
Arreglo=np.zeros((100,100))
for i in np.arange(0,100):
    for j in np.arange(0,100):
            if (i==j):
                Arreglo[i,j]=1
            else:
                Arreglo[i,j]=0

#otra forma mas rapida
#tam=10
#A=np.zeros((tam,tam))
#for i in range(tam):
#    A[i,i]=1

print(Arreglo.shape)
print(Arreglo)
print()

print()

identidad=np.identity(100)
print(identidad)


identidad.dtype

(100, 100)
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


dtype('float64')

**Extra:**
* ¿Qué tipo de dato está usando NumPy cuando crea los arreglos?
Los tipos existentes en NumPy reciben como nombre el tipo básico de datos que contienen, como int, float o complex, y, a continuación, un número indicando el número de bits por elemento.

Para determinar el tipo de dato se puede usar el comando  `().dtype` que indicara el tipo de dato float, int, complejo y la cantidad de bit que usa la maquina 8, 16, 32, 64.

* ¿Y si queremos cambiarle el tipo de dato, por ejemplo a `int`? Googlear "numpy astype". 
Hace un copia de un array aplicándole otro tipo de datos a un array 
ej.crear un array de números a partir de un array que contenga textos representando números:

https://www.interactivechaos.com/manual/tutorial-de-numpy/el-metodo-astype

* ¿Qué pasa si usamos `astype(bool)`?

convierte mi matriz en booleana, solo si la matriz tiene unos y ceros.